[custom]
enable_rule_generator=true
overwrite_original_rules=true
; 基础mihomo配置
clash.http_port=7890
clash.socks_port=7891
clash.allow_lan=true
clash.mode=rule
clash.log_level=info

; ==========【第一步：先定义所有基础组，后面才可以被引用】 ==========
custom_proxy_group=手动选择`select`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`300
custom_proxy_group=自动`url-test`.*`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=Kuromis`select`!!GROUPID=0

; ==========【第二步：再写嵌套引用的代理组】 ==========
custom_proxy_group=社媒信息`select`[]DIRECT`[]手动选择`[]自动选择`[]Kuromis
custom_proxy_group=漏网之鱼`select`[]DIRECT`[]手动选择`[]自动选择`[]Kuromis

; ==========【规则集配置】 ==========
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMax_Classical_No_Resolve.list
ruleset=海外信息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/LinkedIn/LinkedIn.list
ruleset=漏网之鱼,[]MATCH
